# Generated by Django 5.2.6 on 2025-09-14 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('turma', models.CharField(choices=[('1E', '1º Ano Eletro'), ('2E', '2º Ano Eletro'), ('3E', '3º Ano Eletro'), ('1I', '1º Ano Info'), ('2I', '2º Ano Info'), ('3I', '3º Ano Info')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('usuario_login', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRetirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Digital',
            fields=[
                ('sensor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digitais', to='api.aluno')),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digitais', to='api.servidor')),
            ],
        ),
    ]
