# Generated by Django 5.2.6 on 2025-09-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_servidor_usuario_login_servidor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
